// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Answers struct {
	OptionId         uuid.UUID `json:"optionId"`
	QuestionId       uuid.UUID `json:"questionId"`
	ModuleInstanceId uuid.UUID `json:"moduleInstanceId"`
	UpdatedAt        time.Time `json:"updatedAt"`
	CreatedAt        time.Time `json:"createdAt"`
}

type ModuleInstances struct {
	ID               uuid.UUID `json:"id"`
	ModuleId         uuid.UUID `json:"moduleId"`
	TryoutInstanceId uuid.UUID `json:"tryoutInstanceId"`
	Status           string    `json:"status"`
	UpdatedAt        time.Time `json:"updatedAt"`
	CreatedAt        time.Time `json:"createdAt"`
}

type Modules struct {
	ID          uuid.UUID     `json:"id"`
	Title       string        `json:"title"`
	TryoutId    uuid.UUID     `json:"tryoutId"`
	ModuleOrder sql.NullInt32 `json:"moduleOrder"`
	UpdatedAt   time.Time     `json:"updatedAt"`
	CreatedAt   time.Time     `json:"createdAt"`
}

type Options struct {
	ID          uuid.UUID     `json:"id"`
	QuestionId  uuid.UUID     `json:"questionId"`
	Content     string        `json:"content"`
	IsTrue      bool          `json:"isTrue"`
	OptionOrder sql.NullInt32 `json:"optionOrder"`
	UpdatedAt   time.Time     `json:"updatedAt"`
	CreatedAt   time.Time     `json:"createdAt"`
}

type Questions struct {
	ID            uuid.UUID     `json:"id"`
	Content       string        `json:"content"`
	ModuleId      uuid.UUID     `json:"moduleId"`
	QuestionOrder sql.NullInt32 `json:"questionOrder"`
	UpdatedAt     time.Time     `json:"updatedAt"`
	CreatedAt     time.Time     `json:"createdAt"`
}

type Roles struct {
	ID   uuid.UUID `json:"id"`
	Type string    `json:"type"`
}

type Transactions struct {
	ID        uuid.UUID `json:"id"`
	TryoutId  uuid.UUID `json:"tryoutId"`
	Amount    string    `json:"amount"`
	UserId    uuid.UUID `json:"userId"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updatedAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type TryoutInstances struct {
	ID        uuid.UUID `json:"id"`
	UserId    uuid.UUID `json:"userId"`
	TryoutId  uuid.UUID `json:"tryoutId"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updatedAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type Tryouts struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Price     string    `json:"price"`
	Status    string    `json:"status"`
	StartedAt time.Time `json:"startedAt"`
	EndedAt   time.Time `json:"endedAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type Users struct {
	Uid       uuid.UUID      `json:"uid"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	RoleId    uuid.UUID      `json:"roleId"`
	Avatar    sql.NullString `json:"avatar"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}
