// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateModule(ctx context.Context, arg CreateModuleParams) (Modules, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) (Options, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Questions, error)
	CreateTryout(ctx context.Context, arg CreateTryoutParams) (Tryouts, error)
}

var _ Querier = (*Queries)(nil)
