// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tryout.sql

package db

import (
	"context"
	"time"
)

const createTryout = `-- name: CreateTryout :one
INSERT INTO "tryouts" (
        title,
        price,
        status,
        "startedAt",
        "endedAt"
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, price, status, "startedAt", "endedAt", "updatedAt", "createdAt"
`

type CreateTryoutParams struct {
	Title     string    `json:"title"`
	Price     string    `json:"price"`
	Status    string    `json:"status"`
	StartedAt time.Time `json:"startedAt"`
	EndedAt   time.Time `json:"endedAt"`
}

func (q *Queries) CreateTryout(ctx context.Context, arg CreateTryoutParams) (Tryouts, error) {
	row := q.db.QueryRowContext(ctx, createTryout,
		arg.Title,
		arg.Price,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i Tryouts
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Price,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
